apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  selector:
    matchLabels:
      app: linkwarden
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      nodeSelector: 
        kubernetes.io/hostname: andreas-legion
      containers:
        - name: linkwarden
          image: ghcr.io/linkwarden/linkwarden:v2.6.2
          env:
            # Consume the secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                    name: linkwarden-info
                    key: postgres_url
                    optional: false
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                    name: linkwarden-info
                    key: nextauth_secret
                    optional: false                    
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                    name: linkwarden-info
                    key: nextauth_url
                    optional: false         
          ports:
            - containerPort: 3000
              protocol: TCP
              name: linkwarden
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - mountPath: /data/data
              name: linkwarden-storage-vol
      restartPolicy: Always
      volumes:
      - name: linkwarden-storage-vol
        persistentVolumeClaim:
          claimName: linkwarden-storage
