apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkwarden-volume
spec:    
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/linkwarden
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-storage
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
