apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modpacks
  namespace: minecraft
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
